# Generated by Django 4.1.7 on 2023-05-02 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Memorando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=None, null=True)),
                ('memo_numero', models.IntegerField()),
                ('assunto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Digite o assunto')),
                ('corpo_memorando', tinymce.models.HTMLField()),
                ('destinatario', models.ManyToManyField(related_name='memorandos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorandos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
