# Generated by Django 4.1.7 on 2023-05-04 19:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0002_ultimonumero_memorando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorando',
            name='corpo_memorando',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
    ]
