# Generated by Django 4.1.7 on 2023-05-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0004_alter_memorando_memo_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorando',
            old_name='corpo_memorando',
            new_name='corpo',
        ),
    ]
