# Generated by Django 4.1.7 on 2023-05-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0007_alter_memorando_assunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorando',
            name='assunto',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
