# Generated by Django 4.1.7 on 2023-05-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0008_alter_memorando_assunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
