# Generated by Django 4.1.7 on 2023-06-23 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoApp', '0009_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorando',
            name='destinatario_copia',
            field=models.ManyToManyField(related_name='destinatario_copia', to=settings.AUTH_USER_MODEL),
        ),
    ]
