# Generated by Django 4.2.2 on 2023-07-16 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoApp', '0011_remove_memorando_destinatario_copia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofício',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_oficio', models.DateTimeField(default=None, null=True)),
                ('memo_numero_oficio', models.CharField(max_length=220)),
                ('destinatario_oficio', models.CharField(blank=True, max_length=225, null=True)),
                ('destinatarios_copia_oficio', models.CharField(blank=True, max_length=225, null=True)),
                ('assunto_oficio', models.CharField(blank=True, max_length=225, null=True)),
                ('corpo_oficio', tinymce.models.HTMLField(default='', null=True)),
                ('remetente_oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorandos_enviados_oficio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
