# Generated by Django 4.2.2 on 2023-07-16 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoApp', '0012_ofício'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorandoCircular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=None, null=True)),
                ('memo_numero', models.CharField(max_length=220)),
                ('assunto', models.CharField(blank=True, max_length=225, null=True)),
                ('corpo', tinymce.models.HTMLField(default='', null=True)),
                ('destinatario', models.ManyToManyField(related_name='memorandos_recebidos_circular', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorandos_enviados_circular', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
