# Generated by Django 4.2.2 on 2023-07-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0013_memorandocircular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorandocircular',
            old_name='assunto',
            new_name='assunto_circular',
        ),
        migrations.RenameField(
            model_name='memorandocircular',
            old_name='corpo',
            new_name='corpo_circular',
        ),
        migrations.RenameField(
            model_name='memorandocircular',
            old_name='data',
            new_name='data_circular',
        ),
        migrations.RenameField(
            model_name='memorandocircular',
            old_name='destinatario',
            new_name='destinatario_circular',
        ),
        migrations.RenameField(
            model_name='memorandocircular',
            old_name='memo_numero',
            new_name='memo_numero_circular',
        ),
        migrations.RenameField(
            model_name='memorandocircular',
            old_name='remetente',
            new_name='remetente_circular',
        ),
    ]
