# Generated by Django 4.2.2 on 2023-07-18 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoApp', '0014_rename_assunto_memorandocircular_assunto_circular_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ofício',
            new_name='Oficio',
        ),
    ]
