# Generated by Django 4.2.2 on 2023-07-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0017_remove_memorando_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorando',
            name='anexo',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
