# Generated by Django 4.2.2 on 2023-07-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0018_memorando_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.RemoveField(
            model_name='memorando',
            name='anexo',
        ),
        migrations.AddField(
            model_name='memorando',
            name='anexo',
            field=models.ManyToManyField(null=True, related_name='anexo', to='memoApp.image'),
        ),
    ]
