# Generated by Django 4.2.2 on 2023-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0019_alter_image_file_remove_memorando_anexo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorando',
            name='anexo',
        ),
        migrations.AddField(
            model_name='image',
            name='idDoc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='tipoDoc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
