# Generated by Django 4.2.2 on 2023-08-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0020_remove_memorando_anexo_image_iddoc_image_tipodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorando',
            name='assunto',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
