# Generated by Django 4.1.7 on 2023-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0022_alter_memorando_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorando',
            name='endereco',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
