# Generated by Django 4.1.7 on 2023-09-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0023_memorando_endereco_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorandocircular',
            name='endereco_circular',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='endereco_oficio',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
