# Generated by Django 4.2.2 on 2023-09-13 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoApp', '0024_memorandocircular_endereco_circular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorando',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='memorandocircular',
            name='endereco_circular',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='endereco_oficio',
        ),
        migrations.CreateModel(
            name='UserMoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
