# Generated by Django 4.1.7 on 2023-09-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_remove_user_matricula'),
        ('memoApp', '0025_remove_memorando_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=225)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
