# Generated by Django 4.2.5 on 2024-01-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoApp', '0026_groupmoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoc',
            name='acessoTerceiros',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmoc',
            name='endereco',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
