# Generated by Django 4.2.5 on 2024-01-26 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoApp', '0027_usermoc_acessoterceiros_alter_groupmoc_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorando',
            name='creatorUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memorandocircular',
            name='creatorUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user_circular', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oficio',
            name='creatorUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user_oficio', to=settings.AUTH_USER_MODEL),
        ),
    ]
